### ISSUE TITLE
repo structure is not rebar3 compliant

### ISSUE THREAD

**Issue by j-hotlink** [marcelog/cowboy_fastcgi#2]
rebar3 fails to find the src folder within the repo due to it's (non-standard) location (./apps/cowboy_fastcgi/src instead of ./src).

rebar.config
```
{erl_opts, [debug_info, {parse_transform, lager_transform} ]}.
{deps, [
        {lager, {git, "git://github.com/erlang-lager/lager.git", {tag, "3.5.2"}}, [raw] },
        {cowboy, {git, "git://github.com/ninenines/cowboy.git", {tag, "2.0.0"}}, [raw] },
        {cowboy_fastcgi, {git, "git://github.com/marcelog/cowboy_fastcgi.git", {branch, "master"}}}
       ]
}.
```

rebar compile output:

```
$ rebar3 clean && rebar3 compile
===> Cleaning out test...
===> Verifying dependencies...
===> Fetching cowboy ({git,"git://github.com/ninenines/cowboy.git",
                                 {ref,
                                     "d3f15cfd8b2bb4c0c697bd995dfa4546474235ad"}})
===> Fetching cowboy_fastcgi ({git,
                                      "git://github.com/marcelog/cowboy_fastcgi.git",
                                      {branch,"master"}})
===> Dependency failure: Application cowboy_fastcgi not found at the top level of directory /home/jon/test/_build/default/lib/cowboy_fastcgi
```

This stops the project being referenced and updated in rebar.config like any other project (eg. cowboy, lager, ...).

The repo fix is trivial (moving src to the top folder) and it allow the repo to "just work" with rebar.

I'm unsure how to configure rebar3 how to work with the existing structure - can you help?

PS: (also a release tag would be nice for pinning)

**Comment by marcelog** [comment]
This is a full application, **not a dependency**, and it was actually created using the `release` template of rebar3. It is **not** intended to be used as a dependency. It is a full application (although just a sample application to show how to use erl_fastcgi).

**Comment by j-hotlink** [comment]
ah - make sense, thanks.
